In [1]:
import pandas as pd
import numpy as np

import random

In [2]:
# set random seed for reproductivity
random.seed(42)

In [3]:
# Function to generate random date and time within range
def generate_random_datetime(start_date, end_date):
    start_timestamp = pd.to_datetime(start_date).timestamp()
    end_timestamp = pd.to_datetime(end_date).timestamp()
    random_timestamp = random.uniform(start_timestamp, end_timestamp)
    return pd.to_datetime(random_timestamp, unit = 's')

In [4]:
# Function to generate random product name
def generate_product_name():
    products = ['T-shirts', 'Jeans', 'Sneakers', 'Smartphone', 'Headphones', 'Watch', 'Backpack','Laptop']
    return random.choice(products)

In [5]:
# Function to generate random price
def generate_price():
    return round(random.uniform(10,500), 2)

In [6]:
# Function to generate random quantity
def generate_quantity():
    return random.randint(1,10)

In [8]:
# Function to generate random Customer name
def generate_customer_name():
    first_names = [
    "John", "Emma", "Michael", "Sophia", "David",
    "Olivia", "James", "Ava", "William", "Mia"
    ]

    last_names = [
        "Smith", "Johnson", "Brown", "Davis", "Wilson",
        "Miller", "Taylor", "Anderson", "Thomas", "Moore"
    ]
    return random.choice(first_names)+' '+ random.choice(last_names)

In [20]:
# Function to generate random email
def generate_email():
    domains = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com"]
    return f"{random.randint(1,999)}@{random.choice(domains)}"

In [10]:


cities = [
    "Delhi", "Mumbai", "Bengaluru", "Kolkata",
    "Chennai", "Hyderabad", "Pune", "Jaipur"
]

states = [
    "Delhi", "Maharashtra", "Karnataka", "West Bengal",
    "Tamil Nadu", "Telangana", "Rajasthan"
]

def generate_address():
    house_no = random.randint(1, 9999)
    city = random.choice(cities)
    state = random.choice(states)
    pincode = random.randint(100000, 999999)

    return f"{house_no}, {city}, {state} - {pincode}"

In [11]:
# Numbers of row in dataFrame
num_rows = 1000

In [18]:
# Generate data for Data Frame
data = {
'OrderID': ['ORD' + str(i).zfill(4) for i in range(1, num_rows + 1)],
'DateTime': [generate_random_datetime('2022-01-01', '2022-12-31') for _ in range(num_rows)],
'Product': [generate_product_name() for _ in range(num_rows)],
'Price': [generate_price() for _ in range(num_rows)],
'Quantity': [generate_quantity() for _ in range(num_rows)]
}

In [21]:
# Calculate TotalPrice
data['TotalPrice'] = [round(data['Price'] [i] * data['Quantity'][i], 2) for i in range(num_rows)]

# Generate customer-related data
data['CustomerName'] = [generate_customer_name() for _ in range(num_rows)]
data['Email'] = [generate_email() for _ in range(num_rows)]
data['Address'] = [generate_address() for _ in range(num_rows)]

#Create DataFrame
ecommerce_df = pd. DataFrame(data)

# Display the DataFrame
ecommerce_df.head()

,OrderID,DateTime,Product,Price,Quantity,TotalPrice,CustomerName,Email,Address
0,ORD0001,2022-08-21 18:01:57.040781056,Jeans,32.97,7,230.79,Olivia Taylor,148@yahoo.com,"7028, Kolkata, Tamil Nadu - 259903"
1,ORD0002,2022-01-10 02:29:38.247450880,Watch,178.76,3,536.28,Mia Wilson,497@hotmail.com,"8377, Bengaluru, Maharashtra - 394795"
2,ORD0003,2022-04-11 02:39:22.050981632,Watch,325.22,2,650.44,Olivia Wilson,133@gmail.com,"1885, Chennai, Telangana - 359369"
3,ORD0004,2022-03-23 05:58:08.430485248,T-shirts,196.77,9,1770.93,David Johnson,712@yahoo.com,"7032, Kolkata, West Bengal - 840777"
4,ORD0005,2022-09-26 01:48:45.096972544,Backpack,266.99,2,533.98,David Moore,467@hotmail.com,"1689, Bengaluru, Maharashtra - 996398"

In [22]:
ecommerce_df.shape

(1000, 9)

In [23]:
ecommerce_df.columns

Index(['OrderID', 'DateTime', 'Product', 'Price', 'Quantity', 'TotalPrice',
       'CustomerName', 'Email', 'Address'],
      dtype='object')

In [24]:
ecommerce_df

,OrderID,DateTime,Product,Price,Quantity,TotalPrice,CustomerName,Email,Address
0,ORD0001,2022-08-21 18:01:57.040781056,Jeans,32.97,7,230.79,Olivia Taylor,148@yahoo.com,"7028, Kolkata, Tamil Nadu - 259903"
1,ORD0002,2022-01-10 02:29:38.247450880,Watch,178.76,3,536.28,Mia Wilson,497@hotmail.com,"8377, Bengaluru, Maharashtra - 394795"
2,ORD0003,2022-04-11 02:39:22.050981632,Watch,325.22,2,650.44,Olivia Wilson,133@gmail.com,"1885, Chennai, Telangana - 359369"
3,ORD0004,2022-03-23 05:58:08.430485248,T-shirts,196.77,9,1770.93,David Johnson,712@yahoo.com,"7032, Kolkata, West Bengal - 840777"
4,ORD0005,2022-09-26 01:48:45.096972544,Backpack,266.99,2,533.98,David Moore,467@hotmail.com,"1689, Bengaluru, Maharashtra - 996398"
...,...,...,...,...,...,...,...,...,...
995,ORD0996,2022-01-12 21:48:34.135076608,Headphones,26.37,2,52.74,William Taylor,54@outlook.com,"7763, Pune, Rajasthan - 861757"
996,ORD0997,2022-05-15 20:56:58.990214656,T-shirts,19.84,4,79.36,David Moore,440@gmail.com,"4414, Kolkata, Karnataka - 594908"
997,ORD0998,2022-06-11 09:23:40.703374592,Sneakers,137.95,6,827.70,Ava Taylor,445@hotmail.com,"4975, Hyderabad, Maharashtra - 421107"
998,ORD0999,2022-12-13 00:02:59.869759232,Backpack,61.32,8,490.56,Ava Anderson,297@outlook.com,"5468, Hyderabad, Rajasthan - 881413"
999,ORD1000,2022-11-08 09:12:46.399395072,Laptop,177.49,8,1419.92,James Brown,498@gmail.com,"5167, Jaipur, Karnataka - 545957"

In [30]:
#Load the data into a pandas dataFrame named ecommerce_df
#ecommerce_df = pd.read_csv('sales_data.csv')

#Convert the 'DateTime' column to datetime format
ecommerce_df['DateTime'] = pd.to_datetime(ecommerce_df ['DateTime'])

#Assuming you want to analyze sates for a specific time period (start_date and end_date)
start_date= '2022-01-01' # Replace this with your desired start date
end_date ='2022-03-31'    #Replace this with your desired end date

#Filter the DataFrame for the specified time period
sales_period = ecommerce_df[(ecommerce_df['DateTime'] >= start_date) & (ecommerce_df['DateTime'] <= end_date)]

#Calculate total sales revenue by multiplying 'Price' and 'Quantity', then summing up

total_revenue = (sales_period['Price']* sales_period['Quantity']).sum()

print("Total sales revenue for the period from", start_date, "to", end_date, "is:", total_revenue)

Total sales revenue for the period from 2022-01-01 to 2022-03-31 is: 336766.47000000003

In [33]:
import pandas as pd

#Assuming ecommerce_df contains your DataFrame with the given columns

#Group by Product and calculate total sales
total_sales_by_product = ecommerce_df.groupby('Product') ['TotalPrice'].sum().reset_index()

#Sort the results by TotalPrice in descending order
total_sales_by_product = total_sales_by_product.sort_values(by= 'TotalPrice', ascending=False)

#Display the result
print(total_sales_by_product)

      Product  TotalPrice
7       Watch   220850.60
3      Laptop   181228.17
5    Sneakers   181174.89
1  Headphones   180176.12
2       Jeans   160879.37
0    Backpack   159495.21
6    T-shirts   155235.79
4  Smartphone   153383.90

In [34]:
#Assuming ecommerce_df contains your DataFrame with the given columns

#Convert 'DateTime' column to datetime format
ecommerce_df['DateTime'] = pd.to_datetime(ecommerce_df['DateTime'])

# Extract year and month from 'DateTime' column
ecommerce_df['Year'] = ecommerce_df['DateTime'].dt.year
ecommerce_df ['Month'] = ecommerce_df ['DateTime'].dt.month

#Group by Year and Month and calculate total sales
total_sales_by_year_month= ecommerce_df.groupby(['Year', 'Month']) ['TotalPrice'].sum().reset_index()

#Display the result

print(total_sales_by_year_month)

    Year  Month  TotalPrice
0   2022      1   105768.45
1   2022      2   111829.28
2   2022      3   124760.04
3   2022      4   130377.14
4   2022      5    78590.53
5   2022      6   132312.27
6   2022      7   128611.75
7   2022      8   132796.84
8   2022      9   124588.57
9   2022     10   103356.91
10  2022     11   114532.87
11  2022     12   104899.40